# Generated by Django 2.0.6 on 2018-06-21 10:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('recipes', '0004_recipestagindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'recipe categories',
            },
        ),
        migrations.AddField(
            model_name='recipespage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='recipes.RecipesCategory'),
        ),
    ]
